### ISSUE TITLE
Player bugs around

### ISSUE THREAD

**Issue by Malebrios** [NoRelect/HexagonShooter#1]
If you remove all Players but one in the PlayerFactory the remaining player bugs around on the screen and doesn't even start shooting.

**Comment by NoRelect** [comment]
This is the expected behaviour. As there is only one player in the game, he immediately wins, without getting a chance to shoot. As this version of Hexagonshooter does not have a winning screen yet, the screen will freeze for 1 second. After that, the game resets. This causes the player to respawn at a different position thus seeming to bug around.
